### PR TITLE
migrate to Svelte 5 and update Lexical dependency to 0.20

### PR DESCRIPTION
**Pull request by fokx**
This PR contains various commits:
* update lexical related dependencies to latest version(0.20)
* migrate to Svelte 5 using `pnpx sv migrate svelte-5` and manually fix some errors

### CODE REVIEW

**Comment by umaranis** [comment]
About 8 tests are failing, mainly related to Images.

I get the following when trying to add an image.
image

**Comment by umaranis** [comment]
Also, `svelte-check` finds 64 errors and 6 warnings.

Upgrade to `lexical` 20 and `svelte` 5 are major changes and I would suggest to keep them separate.

**Comment by umaranis** [comment]
@fokx , I have upgraded to Svelte 5.
Thanks for your contribution. I have included you as co-author on the relevant commits.

**Comment by fokx** [comment]
Thank you sir. Great job!

**Pull request closed without merging**
